// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1655970208);
user_pref("app.update.lastUpdateTime.region-update-timer", 1655970448);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1655969968);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1655970088);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1655969998);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1655970328);
user_pref("browser.theme.dark-toolbar-theme", false);
user_pref("calendar.timezone.local", "Asia/Ho_Chi_Minh");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1655969954685");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.cache.lastUpdate", 1655970209);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20220520005021");
user_pref("extensions.lastAppVersion", "91.9.1");
user_pref("extensions.lastPlatformVersion", "91.9.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"480406da-a50d-45a8-a2fc-36d88c7a8931\",\"google@search.mozilla.org\":\"311ba0b3-d460-4807-ac9a-2a6a57421280\",\"ddg@search.mozilla.org\":\"476342db-cba1-46a1-a5ea-46b35bea0b64\",\"amazondotcom@search.mozilla.org\":\"7a025b3e-0db7-4764-a4f3-600e6344ab04\",\"wikipedia@search.mozilla.org\":\"3013187b-f943-4a67-beaa-64a123def03e\",\"bing@search.mozilla.org\":\"382de930-2be5-4d0a-87c0-69b77cf21583\"}");
user_pref("idle.lastDailyNotification", 1655971529);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.ui-rdf.version", 32);
user_pref("mailnews.database.global.datastore.id", "ad625980-1ded-44d5-b329-5f44a924f66");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "91.9.1");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("places.database.lastMaintenance", 1655971529);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1655971529);
user_pref("toolkit.telemetry.cachedClientID", "f8cc99fd-9640-4921-a174-554d6dee23be");
user_pref("toolkit.telemetry.previousBuildID", "20220520005021");
